baseURL               = "https://s.eallion.com/"
languageCode          = "zh-CN"
title                 = "蜗牛个人导航"
theme                 = "WebStack-Hugo"
preserveTaxonomyNames = true
disablePathToLower    = true
hasCJKLanguage        = true
publishDir            = "public"                            # 站点静态文件保存目录


[params]
    author        = "eallion"
    description   = "蜗牛个人导航 | Hugo WebStack"
    upload        = "https://s2f.kytta.dev/?text=@eallion@e5n.cc%20%E7%94%B3%E8%AF%B7%E5%9C%A8%E3%80%8C%E8%9C%97%E7%89%9B%E4%B8%AA%E4%BA%BA%E5%AF%BC%E8%88%AA%E3%80%8D%20s.eallion.com%20%E4%B8%AD%E6%B7%BB%E5%8A%A0%E9%93%BE%E6%8E%A5"  # 左侧导航栏的"网站提交"
    about         = "/about"                                # 左侧导航栏的"关于导航"页面 (./about)
    repository    = "https://github.com/eallion"            # 左侧导航栏的"仓库导航"页面 (./repository)
    enablePreLoad = false                                    # 网站完全打开前预加载动画
    textPreLoad   = "蜗牛个人导航"                            # 预加载的动画文字，只有当 enablePreLoad=true 时生效
    expandSidebar = true                                    # 默认展开左侧边导航栏
    logosPath     = "assets/images/logos"                   # 网站每个导航地址 logo 存放地址
    defaultLogo   = "assets/images/logos/default.webp"      # logo 图片资源不存在或者错误时，默认显示的 logo; 该参数如为空，将会一直加载对应的 logo，直至成功
    nightMode     = false                                   # 默认站点为深色 (夜间) 模式
    yiyan         = false                                   # 默认启用一言服务，和今日诗词二选一
    jinrishici    = true                                    # 默认启用今日诗词服务，和一言二选一

[params.seo]
    GoogleAdsClient = ''                                    # Google AdSense 

[params.qweather]
    key = ""

[params.images]
    favicon           = "assets/images/favicon.png"
    searchImageL      = "assets/images/bg-math.jpg"         # 搜索部分浅色背景图
    searchImageD      = "assets/images/bg-math.jpg"         # 搜索部分深色背景图
    logoExpandLight   = "assets/images/favicon.png"
    logoExpandDark    = "assets/images/favicon.png"
    logoCollapseLight = "assets/images/favicon.png"
    logoCollapseDark  = "assets/images/favicon.png"
    
[markup.goldmark.renderer]
    unsafe = true
    hardWraps = true
# autocorrect-disable
[params.footer]
    copyright = '本站内容源自互联网，如有内容侵犯权益，请联系站长删除相关内容，联系邮箱：<img src="/assets/images/email.svg" alt="Email" style="vertical-align: middle;"><br/><br/><a href="https://beian.miit.gov.cn/" target="_blank">浙ICP备16031768号-2</a><br/>Powered By <a href="https://gohugo.io/" target="_blank" rel="noopener noreferrer">Hugo</a> & <a href="https://github.com/shenweiyan/WebStack-Hugo" target="_blank">WebStack</a><br/>&copy; {year} <a href="https://www.eallion.com/" target="_blank">蜗牛</a>个人导航'
# autocorrect-enable

[outputs]
    home = ["HTML", "JSON"] # 为主页添加 JSON 输出格式

[mediaTypes]
    [mediaTypes."application/json"]
        suffixes = ["json"]

[outputFormats]
    [outputFormats.JSON]
        mediaType = "application/json"
        baseName = "index" # 输出为 index.json
        isPlainText = true
